apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s
  labels:
    app: k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s
  template:
    metadata:
      labels:
        app: k8s
    spec:
      containers:
        - name: k8s
          image: 691936972587.dkr.ecr.ap-northeast-1.amazonaws.com/spring/my-spring-app:latest  
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-service
spec:
  selector:
    app: k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
            

            
